### ISSUE TITLE
undefined method `before_filter' for ActionController::Base:Class (NoMethodError)

### ISSUE THREAD

**Issue by thattimc** [hsgubert/turbolinks-form#1]
before_filter is no longer supported on rails 5.1. Any chance to support it on rails 5.1?

**Comment by hsgubert** [comment]
I'm not using rails 5.1 yet so I didn't know about this deprecation. I guess we can just change it for `before_action`.

Would you like to make that change and test it in a Rails 5.1 app? If it works I can accept your pull request.

**Comment by hsgubert** [comment]
Fixed on version 0.0.5
